Vibia\CatalogdbBundle\Entity\Subfamilies:
    type: entity
    table: subfamilies
    indexes:
        id_familia:
            columns:
                - id_familia
        id_subfamilia:
            columns:
                - id_subfamilia
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idSubfamilia:
            type: integer
            nullable: false
            unsigned: false
            column: id_subfamilia
        descripcion:
            type: string
            nullable: false
            length: 255
            fixed: false
        idFamilia:
            type: integer
            nullable: false
            unsigned: false
            column: id_familia
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    lifecycleCallbacks: {  }
