demo_homepage:
    path:     /demo/{name}
    defaults: { _controller: DemoBundle:Default:index }
demo_smarty :
    path:   /demosmarty/{param}
    defaults: { _controller: DemoBundle:Demosmarty:index }
